"use client";
import React, { useRef } from "react";
import {
  RocketLaunchIcon,
  Cog8ToothIcon,
  HandThumbUpIcon,
} from "@heroicons/react/24/solid";
import type { JSX } from "react/jsx-dev-runtime";

interface Card {
  icon: JSX.Element;
  title: { en: string; es: string };
  text: { en: string; es: string };
}

interface Props {
  languageState: boolean;
}

const TechPartnerCarousel: React.FC<Props> = ({ languageState }) => {
  const scrollRef = useRef<HTMLDivElement | null>(null);


  const cards: Card[] = [
    {
      icon: <RocketLaunchIcon className="w-10 h-10 text-[#10dffd]" />,
      title: {
        en: "Overview",
        es: "Descripción General",
      },
      text: {
        en: "A service for entrepreneurs who want to strengthen their ideas through technology. I act as your engineering team, turning concepts into scalable and functional digital solutions.",
        es: "Servicio para emprendedores que buscan potenciar sus ideas mediante tecnología. Actúo como tu equipo de ingeniería, transformando ideas en soluciones digitales escalables y funcionales.",
      },
    },
    {
      icon: <Cog8ToothIcon className="w-10 h-10 text-[#10dffd]" />,
      title: {
        en: "Service Presentation",
        es: "Presentación del Servicio",
      },
      text: {
        en: "Includes strategic diagnosis, solution design, development, implementation, and continuous support to measure impact and optimize results.",
        es: "Incluye diagnóstico estratégico, diseño de solución, desarrollo e implementación, y acompañamiento continuo para medir el impacto y optimizar resultados.",
      },
    },
    {
      icon: <HandThumbUpIcon className="w-10 h-10 text-[#10dffd]" />,
      title: {
        en: "Collaboration Model",
        es: "Modelo de Colaboración",
      },
      text: {
        en: "We work together: you bring the vision and business model, I bring the strategy and technology. In exchange, I receive 10% of the results generated by the technological implementation.",
        es: "Trabajamos en conjunto: tú aportas la visión y el modelo de negocio, yo la estrategia y la tecnología. A cambio, recibo el 10% de los resultados que genere la implementación tecnológica.",
      },
    },
  ];

  const headerText = {
    en: "< Partner for Growth/>",
    es: "< Tecnológico para Crecer/>",
  };

  return (
    <section className="w-full max-w-6xl mx-auto py-10 px-4 relative">
      <h2 className="text-2xl md:text-3xl font-bold text-center mb-8 text-black">
        <span className="text-black">
          {languageState ? headerText.en.split("")[0] : headerText.es.split(" ")[0]}/
        </span>
        {languageState ? "Tech Partner for Growth" : "Aliado Tecnológico para Crecer"}
        <span className="text-black">&gt;</span>
      </h2>


      <div
        ref={scrollRef}
        className="flex overflow-x-auto scroll-smooth space-x-6 pb-4 hide-scrollbar"
      >
        {cards.map((card, index) => (
          <div
            key={index}
            className="min-w-[300px] md:min-w-[400px] bg-white shadow-md rounded-2xl p-6 flex flex-col items-center justify-center text-center border border-gray-200 hover:shadow-xl transition"
          >
            <div className="mb-4 text-color">{card.icon}</div>
            <h3 className="text-xl font-semibold mb-2 text-gray-800">
              {languageState ? card.title.en : card.title.es}
            </h3>
            <p className="text-gray-600 text-sm md:text-base leading-relaxed">
              {languageState ? card.text.en : card.text.es}
            </p>
          </div>
        ))}
      </div>

      <style>{`
        .hide-scrollbar::-webkit-scrollbar {
          display: none;
        }
        .hide-scrollbar {
          -ms-overflow-style: none;
          scrollbar-width: none;
        }
      `}</style>
    </section>
  );
};

export default TechPartnerCarousel;
